id = "dyn"
name = "Dyn"
version = "0.1.2"
schema_version = 1
authors = ["Matthew Dray <mdray@duck.com>"]
description = "Dyn language support"
repository = "https://github.com/17robots/dyn-editors"
languages = ["languages/dyn"]
[lib]
kind = "Rust"
version = "0.7.0"
[grammars.dyn]
repository = "https://github.com/17robots/tree-sitter-dyn.git"
rev = "0cc9d798858f5ceb7659fac61e12ac3a62d547cd"
[language_servers.dyn]
name = "Dyn Language Server"
languages = ["Dyn"]
