#!/usr/bin/env python3
"""Generate editor release pins from shared/release.json; --check detects drift."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

def outputs():
    release = json.loads((ROOT / 'shared/release.json').read_text())
    grammar = release['grammar']
    yield 'zed/extension.toml', f'''id = "dyn"
name = "Dyn"
version = "0.1.0"
schema_version = 1
authors = ["Matthew Dray <mdray@duck.com>"]
description = "Dyn language support"
languages = ["languages/dyn"]
[lib]
kind = "Rust"
version = "0.7.0"
[grammars.dyn]
repository = "{grammar['repository']}"
rev = "{grammar['revision']}"
[language_servers.dyn]
name = "Dyn Language Server"
languages = ["Dyn"]
'''
    yield 'helix/languages.toml', f'''# Generated by scripts/sync.py. Merge into your Helix languages.toml.
[language-server.dyn]
command = "dyn"
args = ["lsp"]

[[language]]
name = "dyn"
scope = "source.dyn"
file-types = ["dyn"]
roots = ["dyn.project", ".git", ".jj"]
comment-tokens = "//"
block-comment-tokens = {{ start = "/*", end = "*/" }}
indent = {{ tab-width = 4, unit = "    " }}
language-servers = ["dyn"]

[language.debugger]
name = "lldb-dap"
transport = "stdio"
command = "lldb-dap"

[[language.debugger.templates]]
name = "binary"
request = "launch"
completion = [{{ name = "binary", completion = "filename" }}]
args = {{ program = "{{0}}", stopOnEntry = false }}

[[grammar]]
name = "dyn"
source = {{ git = "{grammar['repository']}", rev = "{grammar['revision']}" }}
'''
    mason = f'''# Generated by scripts/sync.py. Installs the entire SDK.
name: dyn
description: Dyn compiler and language server (preview).
homepage: https://github.com/{release['repository']}
licenses: [proprietary]
languages: [Dyn]
categories: [Compiler, LSP]
source:
  id: pkg:github/{release['repository']}@v{release['version']}
  asset:
'''
    targets = {'linux-x64': 'linux_x64', 'macos-arm64': 'darwin_arm64', 'windows-x64': 'win_x64'}
    for platform, asset in release['platforms'].items():
        mason += f"    - target: {targets[platform]}\n      file: {asset['asset']}\n      bin: {asset['directory']}/{asset['binary']}\n"
    mason += 'bin:\n  dyn: "{{source.asset.bin}}"\n'
    yield 'mason/packages/dyn/package.yaml', mason
    mise = f'''# Generated by scripts/sync.py. Keep the full SDK.
[tools."github:{release['repository']}"]
version = "{release['version']}"
prerelease = true
strip_components = 1
bin_path = "bin"
[tools."github:{release['repository']}".platforms]
'''
    for platform, asset in release['platforms'].items():
        mise += f'{platform} = {{ asset_pattern = "{asset["asset"]}", checksum = "sha256:{asset["sha256"]}" }}\n'
    yield 'shared/mise.toml', mise

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    stale = []
    for name, content in outputs():
        path = ROOT / name
        if args.check:
            if not path.exists() or path.read_text() != content:
                stale.append(name)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if stale:
        parser.exit(1, 'Generated files are stale: ' + ', '.join(stale) + '\n')
